# -*- coding: utf-8 -*-
"""cobastreamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U7B46D0A2_4JLG2vTZ1MEDKuAHLBfB4k
"""

import streamlit as st

def main():
    st.title("My Streamlit App")
    st.write("Hello, World!")
    st.image("image.png")
    if st.button("Click me!"):
        st.write("Button was clicked!")

if __name__ == '__main__':
    main()